import ArrowForwardIcon from '@mui/icons-material/ArrowForward'
import FavoriteIcon from '@mui/icons-material/Favorite'
import { useState } from 'react'
import type { FormEvent } from 'react'
import { subscribeNewsletter } from './supabase'

type Article = {
  slug: string
  category: string
  title: string
  description: string
  date: string
  isoDate: string
  time: string
  image: string
  opening: string
  sections: { title: string; paragraphs: string[] }[]
}

const articles: Article[] = [
  {
    slug: 'nr1-saude-mental-escolas', category: 'Saúde Mental', date: '10 de junho de 2026', isoDate: '2026-06-10', time: '8 min de leitura', image: '/assets/team.avif',
    title: 'NR-1 e saúde mental nas escolas: o que sua instituição precisa saber',
    description: 'As atualizações da Norma Regulamentadora nº 1 passam a exigir a inclusão de riscos psicossociais no PGR. Entenda o que muda e como se preparar.',
    opening: 'A saúde mental deixou de ser apenas uma pauta de acolhimento para se tornar também uma responsabilidade de gestão. Para instituições de ensino, isso exige processos capazes de identificar riscos psicossociais antes que eles se convertam em afastamentos, conflitos e perda de qualidade pedagógica.',
    sections: [
      { title: 'O que muda para as instituições de ensino', paragraphs: ['A gestão de riscos ocupacionais precisa considerar fatores como sobrecarga, assédio, falta de autonomia, conflitos e exposição contínua a situações emocionalmente exigentes. Na escola, esses fatores atravessam o cotidiano de professores, coordenação, apoio e gestão.', 'Não basta agir somente depois de um afastamento. A instituição precisa demonstrar que reconhece os riscos, acompanha sua evolução e mantém medidas preventivas coerentes com a realidade de cada equipe.'] },
      { title: 'Por que pesquisas anuais não são suficientes', paragraphs: ['Uma fotografia isolada do clima organizacional envelhece rapidamente. Calendário de provas, fechamento de semestre, mudanças de turma e relações com famílias alteram o ambiente ao longo do ano.', 'A escuta contínua permite perceber tendências e direcionar o cuidado sem expor indivíduos. O objetivo não é vigiar pessoas, mas enxergar padrões que permaneciam invisíveis para a gestão.'] },
      { title: 'Como começar a preparação', paragraphs: ['Mapeie os grupos mais expostos, estabeleça uma rotina de escuta, defina responsáveis por analisar os indicadores e documente as ações adotadas. A tecnologia deve simplificar esse ciclo e preservar a privacidade desde a coleta.', 'Com sinais confiáveis em mãos, RH e coordenação conseguem priorizar intervenções, avaliar resultados e construir um ambiente de trabalho mais saudável e sustentável.'] }
    ]
  },
  {
    slug: 'sinais-evasao-escolar', category: 'Evasão Escolar', date: '22 de junho de 2026', isoDate: '2026-06-22', time: '6 min de leitura', image: '/assets/students.avif',
    title: 'Os sinais silenciosos de evasão que sua escola provavelmente está ignorando',
    description: 'A evasão raramente acontece de um dia para o outro. Sinais emocionais e comportamentais aparecem semanas — às vezes meses — antes da saída.',
    opening: 'Quando uma família comunica a transferência, a decisão quase nunca começou naquele dia. Antes dela, surgem pequenos sinais: perda de vínculo, faltas, queda de participação e uma sensação crescente de que ninguém está percebendo o que acontece.',
    sections: [
      { title: 'A evasão começa muito antes da matrícula ser cancelada', paragraphs: ['O desligamento emocional costuma vir primeiro. O aluno participa menos, evita atividades coletivas, deixa de procurar ajuda e passa a enxergar a escola como um lugar onde não pertence.', 'Cada sinal isolado pode parecer comum. Quando observados em conjunto e ao longo do tempo, eles formam um padrão que merece atenção.'] },
      { title: 'Os sinais que merecem acompanhamento', paragraphs: ['Mudanças bruscas de frequência, queda de rendimento, conflitos recorrentes, isolamento e respostas negativas sobre pertencimento são indicadores relevantes. Também importa ouvir as famílias e perceber alterações no relacionamento com professores.', 'A escola precisa combinar dados acadêmicos com uma escuta emocional segura. Só assim deixa de interpretar sofrimento como simples desinteresse.'] },
      { title: 'Da percepção à ação preventiva', paragraphs: ['Um alerta só tem valor quando leva a uma ação cuidadosa. Coordenação e orientação podem abrir uma conversa, revisar o contexto da turma e acionar apoio pedagógico ou psicológico quando necessário.', 'Agir cedo protege o aluno, fortalece a confiança da família e reduz uma perda que afeta toda a comunidade escolar.'] }
    ]
  },
  {
    slug: 'burnout-docente', category: 'Docência', date: '4 de julho de 2026', isoDate: '2026-07-04', time: '10 min de leitura', image: '/assets/teachers.avif',
    title: 'Burnout docente: por que a profissão de professor virou risco psicossocial',
    description: 'A docência reúne fatores de alto risco psicossocial. Veja o que isso significa, na prática, para gestores de RH e coordenadores pedagógicos.',
    opening: 'Ensinar exige presença emocional constante. O professor administra conteúdo, conflitos, expectativas de famílias, demandas administrativas e as necessidades particulares de dezenas de alunos. Quando essa carga se torna crônica, o desgaste deixa de ser apenas cansaço.',
    sections: [
      { title: 'Por que o trabalho docente adoece', paragraphs: ['Sobrecarga, baixa autonomia, pressão por resultados e dificuldade de desconexão criam um cenário de tensão permanente. Muitos profissionais continuam funcionando por meses enquanto perdem energia, confiança e vínculo com o trabalho.', 'O burnout não é falha individual. Ele aponta um desequilíbrio entre as exigências do ambiente e os recursos disponíveis para enfrentá-las.'] },
      { title: 'Os sinais que a gestão costuma perceber tarde', paragraphs: ['Irritabilidade, afastamento da equipe, aumento de faltas, dificuldade de concentração e perda de entusiasmo podem preceder licenças prolongadas. Quando a escola depende apenas de relatos espontâneos, muitos professores silenciam por medo de julgamento.', 'Uma rotina de escuta confidencial oferece uma leitura coletiva do ambiente e ajuda a identificar setores ou períodos de maior pressão.'] },
      { title: 'Cuidado docente também é estratégia educacional', paragraphs: ['Reduzir tarefas redundantes, melhorar a comunicação, garantir pausas e criar canais seguros de apoio são medidas concretas. Os indicadores permitem escolher ações mais precisas e acompanhar se elas realmente melhoram o cotidiano.', 'Cuidar de quem ensina reduz afastamentos e turnover, mas vai além: professores emocionalmente amparados constroem relações mais estáveis e ambientes melhores para aprender.'] }
    ]
  }
]

function Header(){return <header className="sticky top-0 z-50 bg-white text-purple shadow-sm"><div className="content-1920 flex items-center justify-between px-6 py-5 lg:px-10"><a href="/" className="text-[36px] font-black leading-none tracking-[-.065em] text-[#494696]">escuteri<span className="text-coral">a</span></a><nav className="hidden items-center gap-8 md:flex"><a href="/#problema" className="text-sm">O Problema</a><a href="/#como-funciona" className="text-sm">Como Funciona</a><a href="/#vantagens" className="text-sm">Vantagens</a><a href="/#plataforma" className="text-sm">Plataforma</a><a href="/sobre" className="text-sm">Sobre</a><a href="/contato" className="ml-24 rounded-full bg-coral px-6 py-3 text-sm font-bold text-white">Agendar Demo</a></nav></div></header>}

function Footer(){return <footer className="bg-[#0d0719] px-6 py-14 text-white/45 lg:px-9"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[1.8fr_1fr_1fr_1fr]"><div><a href="/" className="text-4xl font-black text-[#ccccff]">escuteri<span className="text-coral">a</span></a><p className="mt-5 max-w-xs text-sm leading-6">A primeira plataforma de escuta ativa com IA para instituições de ensino. Antecipe o cuidado.</p></div>{[['Plataforma',[['Como funciona','/#como-funciona'],['Segurança','/seguranca'],['LGPD','/lgpd'],['White Label','/white-label']]],['Instituições',[['Escolas privadas','/escolas-privadas'],['Redes municipais','/redes-municipais'],['Redes estaduais','/redes-estaduais'],['Universitário','/universitario']]],['Empresa',[['Sobre nós','/sobre'],['Blog','/blog'],['Contato','/contato']]]].map(([title,links])=><div key={title as string}><h4 className="text-xs font-bold uppercase text-white/55">{title as string}</h4><ul className="mt-6 space-y-5 text-sm">{(links as string[][]).map(([name,href])=><li key={name}><a href={href} className="hover:text-white">{name}</a></li>)}</ul></div>)}</div><div className="mx-auto mt-12 flex max-w-7xl flex-col justify-between gap-5 border-t border-white/10 pt-7 text-xs md:flex-row"><p>© 2026 Escuteria. Todos os direitos reservados.</p><span>Feito com <FavoriteIcon className="text-coral align-middle" sx={{fontSize:14}}/> para escolas brasileiras</span></div></footer>}

function Newsletter(){const [status,setStatus]=useState<'idle'|'sending'|'success'|'error'>('idle');async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;setStatus('sending');try{await subscribeNewsletter(String(new FormData(form).get('email')||''));form.reset();setStatus('success')}catch{setStatus('error')}}return <div className="rounded-3xl bg-[#2d1b4d] px-7 py-10 text-center text-white"><h3 className="text-3xl font-black">Receba novos artigos por e-mail</h3><p className="mt-3 text-white/55">Sem spam. Apenas conteúdo relevante sobre saúde mental na educação.</p><form className="mx-auto mt-7 flex max-w-xl flex-col gap-3 sm:flex-row" onSubmit={submit}><input required name="email" type="email" placeholder="seu@email.com" className="min-w-0 flex-1 rounded-full border border-white/20 bg-white/10 px-6 py-4 outline-none placeholder:text-white/40 focus:border-coral"/><button disabled={status==='sending'} className="rounded-full bg-coral px-8 py-4 font-bold disabled:opacity-60">{status==='sending'?'Enviando...':'Inscrever'}</button></form>{status==='success'&&<p className="mt-4 text-sm text-green-300">Inscrição realizada com sucesso.</p>}{status==='error'&&<p className="mt-4 text-sm text-red-300">Não foi possível inscrever agora. Tente novamente.</p>}</div>}

function Card({article,featured=false}:{article:Article;featured?:boolean}){return <a href={`/blog/${article.slug}`} className={`group overflow-hidden rounded-3xl border border-purple/10 ${featured?'grid lg:grid-cols-2':''}`}><div className="overflow-hidden"><img src={article.image} alt={article.title} className={`${featured?'h-full min-h-[390px]':'h-64'} w-full object-cover transition duration-500 group-hover:scale-105`}/></div><div className="flex flex-col justify-center p-8 lg:p-12"><span className="w-fit rounded-full bg-coral/10 px-4 py-2 text-xs font-bold uppercase tracking-[.12em] text-coral">{article.category}</span><h2 className={`mt-6 font-black leading-tight ${featured?'text-4xl':'text-3xl'}`}>{article.title}</h2><p className="mt-5 leading-7 text-purple/55">{article.description}</p><div className="mt-8 flex flex-wrap items-center justify-between gap-3 text-sm"><span className="text-purple/45"><time dateTime={article.isoDate}>{article.date}</time> · {article.time}</span><span className="flex items-center gap-2 font-bold text-coral">Ler artigo <ArrowForwardIcon sx={{fontSize:18}}/></span></div></div></a>}

function BlogIndex(){return <main><Header/><section className="bg-[linear-gradient(135deg,#1b0d32,#382255)] px-6 py-24 text-center text-white"><p className="mb-6 text-xs font-black uppercase tracking-[.3em] text-coral">Blog</p><h1 className="mx-auto max-w-4xl text-5xl font-black leading-[1.08] tracking-[-.05em] sm:text-6xl">Conteúdo sobre saúde mental na educação.</h1><p className="mx-auto mt-7 max-w-2xl text-lg leading-8 text-white/55">Artigos, pesquisas e reflexões para gestores, coordenadores e equipes pedagógicas.</p></section><section className="bg-white px-6 py-20 lg:px-10"><div className="mx-auto max-w-7xl"><Card article={articles[0]} featured/><div className="mt-8 grid gap-8 md:grid-cols-2">{articles.slice(1).map(article=><Card key={article.slug} article={article}/>)}</div><div className="mt-16"><Newsletter/></div></div></section><Footer/></main>}

function ArticlePage({article}:{article:Article}){return <main><Header/><article><header className="bg-[#170b2c] px-6 py-20 text-white"><div className="mx-auto max-w-4xl"><a href="/blog" className="text-sm font-bold text-coral">← Voltar ao blog</a><p className="mt-12 text-xs font-black uppercase tracking-[.22em] text-coral">{article.category}</p><h1 className="mt-5 text-4xl font-black leading-[1.08] tracking-[-.045em] sm:text-6xl">{article.title}</h1><div className="mt-7 text-sm text-white/50"><time dateTime={article.isoDate}>{article.date}</time> · {article.time}</div></div></header><img src={article.image} alt={article.title} className="h-[320px] w-full object-cover sm:h-[480px]"/><div className="mx-auto max-w-3xl px-6 py-16"><p className="text-xl font-medium leading-9 text-purple/75">{article.opening}</p>{article.sections.map(section=><section key={section.title} className="mt-14"><h2 className="text-3xl font-black leading-tight tracking-[-.03em]">{section.title}</h2>{section.paragraphs.map(paragraph=><p key={paragraph} className="mt-6 text-lg leading-8 text-purple/65">{paragraph}</p>)}</section>)}<div className="mt-16 border-t border-purple/10 pt-12"><Newsletter/></div></div></article><Footer/></main>}

export function BlogExperience({path}:{path:string}){if(path==='/blog'||path==='/blog/')return <BlogIndex/>;const slug=path.replace(/^\/blog\//,'').replace(/\/$/,'');const article=articles.find(item=>item.slug===slug);if(article)return <ArticlePage article={article}/>;return <main><Header/><section className="grid min-h-[60vh] place-items-center bg-[#170b2c] px-6 text-center text-white"><div><p className="text-coral">404</p><h1 className="mt-4 text-5xl font-black">Artigo não encontrado.</h1><a href="/blog" className="mt-8 inline-block rounded-full bg-coral px-7 py-4 font-bold">Voltar ao blog</a></div></section><Footer/></main>}
